### ISSUE TITLE
hope to add a blank about ShrinkFactor in set solver attributes

### ISSUE THREAD

**Issue by shaobosong** [pointwise/CaeUnsOpenFOAM#1]

**Comment by dbgarlisch** [comment]
I am not understanding the problem.
Please provide more information.

**Comment by shaobosong** [comment]
@dbgarlisch ,i'm sorry about this, i'm a freshman for Openfoam and Pointwise. i just hope that plugin having a function 'shrink factor', which can scale up or down cell's size in file 'points'. Because for Openfoam,  cell has its unit, that is meter(m), but i always forget this, and still use millimeter(mm) as unit i like. I don't know if Pointwise or Openfoam has included similar function or not. If function is included, please tell me how to use it. Thank you very much!
and i make some change, such as
fprintf(*this, "(%.*g %.*g %.*g)\n", p, v.x, p, v.y, p, v.z);
to
fprintf(*this, "(%.*g %.*g %.*g)\n", p, v.x*0.001, p, v.y*0.001, p, v.z*0.001);
according to my own habit.

**Comment by dbgarlisch** [comment]
The OpenFOAM plugin does not support grid scaling.

You will need to apply the scaling transform in Pointwise before exporting
the grid data.

Use Edit, Transform, Scale...

Also, in the future, it would be best to ask Pointwise and other CFD
questions at. https://www.cfd-online.com/Forums/pointwise/

Good luck with your grid.


On Sep 28, 2017 8:36 PM, "sungda" <notifications@github.com> wrote:

@dbgarlisch <https://github.com/dbgarlisch> ,i'm sorry about this, i'm a
freshman for Openfoam and Pointwise. i just hope that plugin having a
function 'shrink factor', which can scale up or down cell's size in file
'points'. Because for Openfoam, cell has its unit, that is meter(m), but i
always forget this, and still use millimeter(mm) as unit i like. I don't
know if Pointwise or Openfoam has included similar function or not. If
function is included, please tell me how to use it. Thank you very much!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pointwise/CaeUnsOpenFOAM/issues/1#issuecomment-333007702>,
or mute the thread

**Comment by shaobosong** [comment]
@dbgarlisch ,thank you again !
